# Generated by Django 4.2.5 on 2023-09-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
